server:
  port: 80

spring:
  h2:
    console:
      enabled: true
      path: /db
  
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/test/h2db;AUTO_SERVER=TRUE
    username: test
    password: 1234

  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace
